import json
import os

# Hand-curated, high-quality quotes with deep meaning.
# 50 per tome.
tomes_data = {
    "universal": [
        {"text": "The impediment to action advances action. What stands in the way becomes the way.", "attribution": "Marcus Aurelius", "weight": 8},
        {"text": "We suffer more often in imagination than in reality.", "attribution": "Seneca", "weight": 8},
        {"text": "Nature does not hurry, yet everything is accomplished.", "attribution": "Lao Tzu", "weight": 7},
        {"text": "To know what you know and what you do not know, that is true knowledge.", "attribution": "Confucius", "weight": 6},
        {"text": "The only true wisdom is in knowing you know nothing.", "attribution": "Socrates", "weight": 9},
        {"text": "He who has a why to live for can bear almost any how.", "attribution": "Friedrich Nietzsche", "weight": 8},
        {"text": "In the midst of chaos, there is also opportunity.", "attribution": "Sun Tzu", "weight": 7},
        {"text": "The journey of a thousand miles begins with one step.", "attribution": "Lao Tzu", "weight": 6},
        {"text": "Happiness depends upon ourselves.", "attribution": "Aristotle", "weight": 7},
        {"text": "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", "attribution": "Heraclitus", "weight": 8},
        {"text": "Do not say a little in many words but a great deal in few.", "attribution": "Pythagoras", "weight": 6},
        {"text": "It is not death that a man should fear, but he should fear never beginning to live.", "attribution": "Marcus Aurelius", "weight": 9},
        {"text": "To live is the rarest thing in the world. Most people exist, that is all.", "attribution": "Oscar Wilde", "weight": 8},
        {"text": "The soul becomes dyed with the color of its thoughts.", "attribution": "Marcus Aurelius", "weight": 8},
        {"text": "Life is what happens when you're busy making other plans.", "attribution": "John Lennon", "weight": 5},
        {"text": "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'", "attribution": "Lao Tzu", "weight": 7},
        {"text": "The unexamined life is not worth living.", "attribution": "Socrates", "weight": 9},
        {"text": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "attribution": "Will Durant", "weight": 8},
        {"text": "Even a stopped clock is right twice every day.", "attribution": "Marie von Ebner-Eschenbach", "weight": 5},
        {"text": "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", "attribution": "J.K. Rowling", "weight": 6},
        {"text": "Out of the mountain of despair, a stone of hope.", "attribution": "Martin Luther King Jr.", "weight": 7},
        {"text": "Turn your wounds into wisdom.", "attribution": "Oprah Winfrey", "weight": 6},
        {"text": "He who fears he will suffer, already suffers because he fears.", "attribution": "Michel de Montaigne", "weight": 8},
        {"text": "Sometimes even to live is an act of courage.", "attribution": "Seneca", "weight": 9},
        {"text": "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", "attribution": "Epictetus", "weight": 8},
        {"text": "Wealth consists not in having great possessions, but in having few wants.", "attribution": "Epictetus", "weight": 7},
        {"text": "Man conquers the world by conquering himself.", "attribution": "Zeno of Citium", "weight": 8},
        {"text": "It is not the man who has too little, but the man who craves more, that is poor.", "attribution": "Seneca", "weight": 7},
        {"text": "First say to yourself what you would be; and then do what you have to do.", "attribution": "Epictetus", "weight": 8},
        {"text": "Waste no more time arguing about what a good man should be. Be one.", "attribution": "Marcus Aurelius", "weight": 9},
        {"text": "The best revenge is to be unlike him who performed the injury.", "attribution": "Marcus Aurelius", "weight": 8},
        {"text": "Difficulties strengthen the mind, as labor does the body.", "attribution": "Seneca", "weight": 7},
        {"text": "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", "attribution": "Epictetus", "weight": 8},
        {"text": "Ignorance is the cause of fear.", "attribution": "Seneca", "weight": 7},
        {"text": "You have power over your mind - not outside events. Realize this, and you will find strength.", "attribution": "Marcus Aurelius", "weight": 9},
        {"text": "A ship is safe in harbor, but that's not what ships are for.", "attribution": "John A. Shedd", "weight": 8},
        {"text": "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.", "attribution": "Confucius", "weight": 8},
        {"text": "I hear and I forget. I see and I remember. I do and I understand.", "attribution": "Confucius", "weight": 7},
        {"text": "It does not matter how slowly you go as long as you do not stop.", "attribution": "Confucius", "weight": 8},
        {"text": "Everything has beauty, but not everyone sees it.", "attribution": "Confucius", "weight": 6},
        {"text": "When anger rises, think of the consequences.", "attribution": "Confucius", "weight": 7},
        {"text": "The more you know, the less you need.", "attribution": "Yvon Chouinard", "weight": 6},
        {"text": "Care about what other people think and you will always be their prisoner.", "attribution": "Lao Tzu", "weight": 8},
        {"text": "New beginnings are often disguised as painful endings.", "attribution": "Lao Tzu", "weight": 8},
        {"text": "Do the difficult things while they are easy and do the great things while they are small.", "attribution": "Lao Tzu", "weight": 7},
        {"text": "Simplicity is the ultimate sophistication.", "attribution": "Leonardo da Vinci", "weight": 7},
        {"text": "The mind is everything. What you think you become.", "attribution": "Buddha", "weight": 8},
        {"text": "Three things cannot be long hidden: the sun, the moon, and the truth.", "attribution": "Buddha", "weight": 9},
        {"text": "You will not be punished for your anger, you will be punished by your anger.", "attribution": "Buddha", "weight": 8},
        {"text": "Peace comes from within. Do not seek it without.", "attribution": "Buddha", "weight": 7}
    ],
    "love": [
        {"text": "The minute I heard my first love story, I started looking for you.", "attribution": "Rumi", "weight": 8},
        {"text": "Whatever our souls are made of, his and mine are the same.", "attribution": "Emily Brontë", "weight": 9},
        {"text": "Doubt thou the stars are fire; Doubt that the sun doth move; Doubt truth to be a liar; But never doubt I love.", "attribution": "William Shakespeare", "weight": 8},
        {"text": "If I know what love is, it is because of you.", "attribution": "Hermann Hesse", "weight": 7},
        {"text": "Love is composed of a single soul inhabiting two bodies.", "attribution": "Aristotle", "weight": 8},
        {"text": "Where there is love there is life.", "attribution": "Mahatma Gandhi", "weight": 6},
        {"text": "We loved with a love that was more than love.", "attribution": "Edgar Allan Poe", "weight": 8},
        {"text": "There is no remedy for love but to love more.", "attribution": "Henry David Thoreau", "weight": 7},
        {"text": "Love is a friendship set to music.", "attribution": "Joseph Campbell", "weight": 6},
        {"text": "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.", "attribution": "Oscar Wilde", "weight": 7},
        {"text": "To love and be loved is to feel the sun from both sides.", "attribution": "David Viscott", "weight": 7},
        {"text": "Love takes off masks that we fear we cannot live without and know we cannot live within.", "attribution": "James Baldwin", "weight": 9},
        {"text": "The greatest thing you'll ever learn is just to love and be loved in return.", "attribution": "Eden Ahbez", "weight": 8},
        {"text": "Love does not consist in gazing at each other, but in looking outward together in the same direction.", "attribution": "Antoine de Saint-Exupéry", "weight": 9},
        {"text": "Let yourself be drawn by the stronger pull of that which you truly love.", "attribution": "Rumi", "weight": 8},
        {"text": "Goodbyes are only for those who love with their eyes. Because for those who love with heart and soul there is no such thing as separation.", "attribution": "Rumi", "weight": 9},
        {"text": "Words are a pretext. It is the inner bond that draws one person to another, not words.", "attribution": "Rumi", "weight": 8},
        {"text": "Set your life on fire. Seek those who fan your flames.", "attribution": "Rumi", "weight": 8},
        {"text": "Lovers don't finally meet somewhere. They're in each other all along.", "attribution": "Rumi", "weight": 9},
        {"text": "A flower cannot blossom without sunshine, and man cannot live without love.", "attribution": "Max Müller", "weight": 6},
        {"text": "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", "attribution": "Lao Tzu", "weight": 9},
        {"text": "There is always some madness in love. But there is also always some reason in madness.", "attribution": "Friedrich Nietzsche", "weight": 8},
        {"text": "Love is an untamed force. When we try to control it, it destroys us.", "attribution": "Paulo Coelho", "weight": 7},
        {"text": "Two people in love, alone, isolated from the world, that's beautiful.", "attribution": "Milan Kundera", "weight": 7},
        {"text": "One word frees us of all the weight and pain of life: That word is love.", "attribution": "Sophocles", "weight": 8},
        {"text": "Love understands love; it needs no talk.", "attribution": "Frances Ridley Havergal", "weight": 6},
        {"text": "We are most alive when we're in love.", "attribution": "John Updike", "weight": 7},
        {"text": "The heart has its reasons of which reason knows nothing.", "attribution": "Blaise Pascal", "weight": 9},
        {"text": "Love is all we have, the only way that each can help the other.", "attribution": "Euripides", "weight": 8},
        {"text": "It is better to have loved and lost than never to have loved at all.", "attribution": "Alfred Lord Tennyson", "weight": 7},
        {"text": "Love looks not with the eyes, but with the mind.", "attribution": "William Shakespeare", "weight": 8},
        {"text": "My bounty is as boundless as the sea, My love as deep.", "attribution": "William Shakespeare", "weight": 8},
        {"text": "The course of true love never did run smooth.", "attribution": "William Shakespeare", "weight": 7},
        {"text": "Love is a smoke made with the fume of sighs.", "attribution": "William Shakespeare", "weight": 6},
        {"text": "If music be the food of love, play on.", "attribution": "William Shakespeare", "weight": 7},
        {"text": "Love is trembling happiness.", "attribution": "Kahlil Gibran", "weight": 5},
        {"text": "Ever has it been that love knows not its own depth until the hour of separation.", "attribution": "Kahlil Gibran", "weight": 9},
        {"text": "Love possesses not nor would it be possessed; For love is sufficient unto love.", "attribution": "Kahlil Gibran", "weight": 8},
        {"text": "If you love somebody, let them go, for if they return, they were always yours.", "attribution": "Kahlil Gibran", "weight": 8},
        {"text": "Love is the only force capable of transforming an enemy into friend.", "attribution": "Martin Luther King Jr.", "weight": 9},
        {"text": "I have decided to stick with love. Hate is too great a burden to bear.", "attribution": "Martin Luther King Jr.", "weight": 8},
        {"text": "True love comes quietly, without banners or flashing lights.", "attribution": "Erich Segal", "weight": 7},
        {"text": "Love is a canvas furnished by nature and embroidered by imagination.", "attribution": "Voltaire", "weight": 6},
        {"text": "He who loves, flies, runs, and rejoices; he is free and nothing holds him back.", "attribution": "Henri Matisse", "weight": 7},
        {"text": "Gravitation is not responsible for people falling in love.", "attribution": "Albert Einstein", "weight": 7},
        {"text": "To love is to recognize yourself in another.", "attribution": "Eckhart Tolle", "weight": 8},
        {"text": "You can't blame gravity for falling in love.", "attribution": "Albert Einstein", "weight": 5},
        {"text": "Love is a better teacher than duty.", "attribution": "Albert Einstein", "weight": 8},
        {"text": "Love is space and time measured by the heart.", "attribution": "Marcel Proust", "weight": 7},
        {"text": "Absence diminishes small loves and increases great ones.", "attribution": "François de La Rochefoucauld", "weight": 8}
    ],
    "fire": [
        {"text": "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", "attribution": "Sun Tzu", "weight": 9},
        {"text": "Veni, vidi, vici. (I came, I saw, I conquered.)", "attribution": "Julius Caesar", "weight": 8},
        {"text": "If you are going through hell, keep going.", "attribution": "Winston Churchill", "weight": 9},
        {"text": "Courage is not having the strength to go on; it is going on when you don't have the strength.", "attribution": "Theodore Roosevelt", "weight": 8},
        {"text": "Victory belongs to the most persevering.", "attribution": "Napoleon Bonaparte", "weight": 7},
        {"text": "Never interrupt your enemy when he is making a mistake.", "attribution": "Napoleon Bonaparte", "weight": 8},
        {"text": "The bold are helpless without cleverness.", "attribution": "Euripides", "weight": 7},
        {"text": "Fortune favors the bold.", "attribution": "Virgil", "weight": 8},
        {"text": "Do not pray for an easy life, pray for the strength to endure a difficult one.", "attribution": "Bruce Lee", "weight": 9},
        {"text": "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "attribution": "Bruce Lee", "weight": 8},
        {"text": "Be formless, shapeless, like water.", "attribution": "Bruce Lee", "weight": 7},
        {"text": "To know your Enemy, you must become your Enemy.", "attribution": "Sun Tzu", "weight": 8},
        {"text": "Appear weak when you are strong, and strong when you are weak.", "attribution": "Sun Tzu", "weight": 9},
        {"text": "The supreme art of war is to subdue the enemy without fighting.", "attribution": "Sun Tzu", "weight": 10},
        {"text": "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", "attribution": "Sun Tzu", "weight": 9},
        {"text": "Opportunities multiply as they are seized.", "attribution": "Sun Tzu", "weight": 8},
        {"text": "Move swift as the Wind and closely-formed as the Wood.", "attribution": "Sun Tzu", "weight": 7},
        {"text": "It is fatal to enter any war without the will to win it.", "attribution": "Douglas MacArthur", "weight": 7},
        {"text": "Only the dead have seen the end of war.", "attribution": "Plato", "weight": 9},
        {"text": "I came, I saw, I conquered.", "attribution": "Julius Caesar", "weight": 8},
        {"text": "The die is cast.", "attribution": "Julius Caesar", "weight": 7},
        {"text": "If you must break the law, do it to seize power: in all other cases observe it.", "attribution": "Julius Caesar", "weight": 8},
        {"text": "A leader is a dealer in hope.", "attribution": "Napoleon Bonaparte", "weight": 7},
        {"text": "Death is nothing, but to live defeated and inglorious is to die daily.", "attribution": "Napoleon Bonaparte", "weight": 9},
        {"text": "He who fears being conquered is sure of defeat.", "attribution": "Napoleon Bonaparte", "weight": 8},
        {"text": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "attribution": "Winston Churchill", "weight": 9},
        {"text": "History will be kind to me for I intend to write it.", "attribution": "Winston Churchill", "weight": 8},
        {"text": "Continuous effort - not strength or intelligence - is the key to unlocking our potential.", "attribution": "Winston Churchill", "weight": 7},
        {"text": "We are masters of the unsaid words, but slaves of those we let slip out.", "attribution": "Winston Churchill", "weight": 8},
        {"text": "To improve is to change; to be perfect is to change often.", "attribution": "Winston Churchill", "weight": 7},
        {"text": "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", "attribution": "Colin Powell", "weight": 7},
        {"text": "Great leaders are almost always great simplifiers.", "attribution": "Colin Powell", "weight": 6},
        {"text": "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.", "attribution": "Alexander the Great", "weight": 9},
        {"text": "There is nothing impossible to him who will try.", "attribution": "Alexander the Great", "weight": 8},
        {"text": "Whatever you do, do it with all your might.", "attribution": "Marcus Tullius Cicero", "weight": 7},
        {"text": "Action is the foundational key to all success.", "attribution": "Pablo Picasso", "weight": 7},
        {"text": "Only those who dare to fail greatly can ever achieve greatly.", "attribution": "Robert F. Kennedy", "weight": 8},
        {"text": "The harder the conflict, the more glorious the triumph.", "attribution": "Thomas Paine", "weight": 9},
        {"text": "These are the times that try men's souls.", "attribution": "Thomas Paine", "weight": 7},
        {"text": "Lead me, follow me, or get out of my way.", "attribution": "George S. Patton", "weight": 8},
        {"text": "Accept the challenges so that you can feel the exhilaration of victory.", "attribution": "George S. Patton", "weight": 7},
        {"text": "A good plan violently executed now is better than a perfect plan executed next week.", "attribution": "George S. Patton", "weight": 9},
        {"text": "It is foolish and wrong to mourn the men who died. Rather we should thank God that such men lived.", "attribution": "George S. Patton", "weight": 8},
        {"text": "Courage is fear holding on a minute longer.", "attribution": "George S. Patton", "weight": 8},
        {"text": "The only tired I was, was tired of giving in.", "attribution": "Rosa Parks", "weight": 9},
        {"text": "You must be the change you wish to see in the world.", "attribution": "Mahatma Gandhi", "weight": 8},
        {"text": "First they ignore you, then they laugh at you, then they fight you, then you win.", "attribution": "Mahatma Gandhi", "weight": 9},
        {"text": "The weak can never forgive. Forgiveness is the attribute of the strong.", "attribution": "Mahatma Gandhi", "weight": 8},
        {"text": "Strength does not come from physical capacity. It comes from an indomitable will.", "attribution": "Mahatma Gandhi", "weight": 9},
        {"text": "Freedom is not worth having if it does not include the freedom to make mistakes.", "attribution": "Mahatma Gandhi", "weight": 7}
    ],
    "brutal": [
        {"text": "Man is condemned to be free.", "attribution": "Jean-Paul Sartre", "weight": 9},
        {"text": "Hell is other people.", "attribution": "Jean-Paul Sartre", "weight": 9},
        {"text": "I am looking for a human.", "attribution": "Diogenes", "weight": 8},
        {"text": "To live is to suffer, to survive is to find some meaning in the suffering.", "attribution": "Friedrich Nietzsche", "weight": 9},
        {"text": "The world breaks everyone and afterward many are strong at the broken places.", "attribution": "Ernest Hemingway", "weight": 8},
        {"text": "We are all in the gutter, but some of us are looking at the stars.", "attribution": "Oscar Wilde", "weight": 8},
        {"text": "People do not wish to appear foolish; to avoid the appearance of foolishness, they are willing to remain actually fools.", "attribution": "Alice Walker", "weight": 7},
        {"text": "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.", "attribution": "Oscar Wilde", "weight": 9},
        {"text": "You will never do anything in this world without courage. It is the greatest quality of the mind next to honor.", "attribution": "Aristotle", "weight": 8},
        {"text": "The truth will set you free, but first it will piss you off.", "attribution": "Gloria Steinem", "weight": 8},
        {"text": "If you tell the truth, you don't have to remember anything.", "attribution": "Mark Twain", "weight": 7},
        {"text": "It's easier to fool people than to convince them that they have been fooled.", "attribution": "Mark Twain", "weight": 9},
        {"text": "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", "attribution": "Mark Twain", "weight": 8},
        {"text": "The secret of getting ahead is getting started.", "attribution": "Mark Twain", "weight": 6},
        {"text": "Man is the only animal that blushes. Or needs to.", "attribution": "Mark Twain", "weight": 8},
        {"text": "The individual has always had to struggle to keep from being overwhelmed by the tribe.", "attribution": "Friedrich Nietzsche", "weight": 9},
        {"text": "He who fights with monsters should look to it that he himself does not become a monster.", "attribution": "Friedrich Nietzsche", "weight": 10},
        {"text": "There are no facts, only interpretations.", "attribution": "Friedrich Nietzsche", "weight": 8},
        {"text": "What does not kill me makes me stronger.", "attribution": "Friedrich Nietzsche", "weight": 8},
        {"text": "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", "attribution": "Friedrich Nietzsche", "weight": 9},
        {"text": "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.", "attribution": "Friedrich Nietzsche", "weight": 9},
        {"text": "God is dead. God remains dead. And we have killed him.", "attribution": "Friedrich Nietzsche", "weight": 10},
        {"text": "We love life, not because we are used to living but because we are used to loving.", "attribution": "Friedrich Nietzsche", "weight": 7},
        {"text": "I cannot teach anybody anything. I can only make them think.", "attribution": "Socrates", "weight": 7},
        {"text": "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.", "attribution": "Socrates", "weight": 8},
        {"text": "Be kind, for everyone you meet is fighting a hard battle.", "attribution": "Socrates", "weight": 8},
        {"text": "Wonder is the beginning of wisdom.", "attribution": "Socrates", "weight": 6},
        {"text": "Education is the kindling of a flame, not the filling of a vessel.", "attribution": "Socrates", "weight": 7},
        {"text": "The only good is knowledge and the only evil is ignorance.", "attribution": "Socrates", "weight": 8},
        {"text": "The mass of men lead lives of quiet desperation.", "attribution": "Henry David Thoreau", "weight": 9},
        {"text": "Things do not change; we change.", "attribution": "Henry David Thoreau", "weight": 8},
        {"text": "It's not what you look at that matters, it's what you see.", "attribution": "Henry David Thoreau", "weight": 7},
        {"text": "I went to the woods because I wished to live deliberately.", "attribution": "Henry David Thoreau", "weight": 8},
        {"text": "Rather than love, than money, than fame, give me truth.", "attribution": "Henry David Thoreau", "weight": 9},
        {"text": "Any fool can know. The point is to understand.", "attribution": "Albert Einstein", "weight": 8},
        {"text": "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "attribution": "Albert Einstein", "weight": 9},
        {"text": "Life is a tragedy when seen in close-up, but a comedy in long-shot.", "attribution": "Charlie Chaplin", "weight": 8},
        {"text": "A day without laughter is a day wasted.", "attribution": "Charlie Chaplin", "weight": 6},
        {"text": "We think too much and feel too little.", "attribution": "Charlie Chaplin", "weight": 7},
        {"text": "The mirror is a worthless invention. The only way to truly see yourself is in the reflection of someone else's eyes.", "attribution": "Voltaire", "weight": 8},
        {"text": "Judge a man by his questions rather than by his answers.", "attribution": "Voltaire", "weight": 9},
        {"text": "Common sense is not so common.", "attribution": "Voltaire", "weight": 7},
        {"text": "Every man is guilty of all the good he did not do.", "attribution": "Voltaire", "weight": 9},
        {"text": "Doubt is an uncomfortable condition, but certainty is a ridiculous one.", "attribution": "Voltaire", "weight": 8},
        {"text": "Life is thickly sown with thorns, and I know no other remedy than to pass quickly through them.", "attribution": "Voltaire", "weight": 8},
        {"text": "To hold a pen is to be at war.", "attribution": "Voltaire", "weight": 7},
        {"text": "Tears are the silent language of grief.", "attribution": "Voltaire", "weight": 6},
        {"text": "Fools have a habit of believing that everything written by a famous author is admirable.", "attribution": "Voltaire", "weight": 8},
        {"text": "Illusion is the first of all pleasures.", "attribution": "Voltaire", "weight": 7},
        {"text": "Prejudices are what fools use for reason.", "attribution": "Voltaire", "weight": 8}
    ],
    "midnight": [
        {"text": "I became insane, with long intervals of horrible sanity.", "attribution": "Edgar Allan Poe", "weight": 9},
        {"text": "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.", "attribution": "H.P. Lovecraft", "weight": 10},
        {"text": "All that we see or seem is but a dream within a dream.", "attribution": "Edgar Allan Poe", "weight": 9},
        {"text": "Deep into that darkness peering, long I stood there wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.", "attribution": "Edgar Allan Poe", "weight": 10},
        {"text": "I love the dark hours of my being.", "attribution": "Rainer Maria Rilke", "weight": 8},
        {"text": "There are nights when the wolves are silent and only the moon howls.", "attribution": "George Carlin", "weight": 8},
        {"text": "I often think that the night is more alive and more richly colored than the day.", "attribution": "Vincent Van Gogh", "weight": 8},
        {"text": "Night is a time of rigor, but also of mercy.", "attribution": "Isaac Bashevis Singer", "weight": 7},
        {"text": "To the mind that is still, the whole universe surrenders.", "attribution": "Lao Tzu", "weight": 9},
        {"text": "Do not go gentle into that good night.", "attribution": "Dylan Thomas", "weight": 10},
        {"text": "We are such stuff as dreams are made on, and our little life is rounded with a sleep.", "attribution": "William Shakespeare", "weight": 9},
        {"text": "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.", "attribution": "William Shakespeare", "weight": 8},
        {"text": "Hell is empty and all the devils are here.", "attribution": "William Shakespeare", "weight": 9},
        {"text": "The night is darkest just before the dawn.", "attribution": "Thomas Fuller", "weight": 7},
        {"text": "I have loved the stars too fondly to be fearful of the night.", "attribution": "Sarah Williams", "weight": 8},
        {"text": "Listen to them, the children of the night. What music they make!", "attribution": "Bram Stoker", "weight": 9},
        {"text": "There are darknesses in life and there are lights, and you are one of the lights, the light of all lights.", "attribution": "Bram Stoker", "weight": 8},
        {"text": "Despair has its own calms.", "attribution": "Bram Stoker", "weight": 8},
        {"text": "No man knows till he has suffered from the night how sweet and dear to his heart and eye the morning can be.", "attribution": "Bram Stoker", "weight": 7},
        {"text": "We live in a flickering patch of light.", "attribution": "Arthur Machen", "weight": 8},
        {"text": "The moon is a friend for the lonesome to talk to.", "attribution": "Carl Sandburg", "weight": 6},
        {"text": "The night walked down the sky with the moon in her hand.", "attribution": "Frederic Lawrence Knowles", "weight": 7},
        {"text": "That is the terror: to have emerged from nothing, to see the world, and then to fall back into nothing.", "attribution": "Milan Kundera", "weight": 9},
        {"text": "Silence is the sleep that nourishes wisdom.", "attribution": "Francis Bacon", "weight": 8},
        {"text": "I must go in, the fog is rising.", "attribution": "Emily Dickinson", "weight": 8},
        {"text": "Hope is the thing with feathers that perches in the soul.", "attribution": "Emily Dickinson", "weight": 8},
        {"text": "Because I could not stop for Death – He kindly stopped for me.", "attribution": "Emily Dickinson", "weight": 9},
        {"text": "The brain is wider than the sky.", "attribution": "Emily Dickinson", "weight": 8},
        {"text": "I felt a Funeral, in my Brain.", "attribution": "Emily Dickinson", "weight": 9},
        {"text": "There's a certain Slant of light, Winter Afternoons.", "attribution": "Emily Dickinson", "weight": 7},
        {"text": "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.", "attribution": "Stephen King", "weight": 9},
        {"text": "Books are a uniquely portable magic.", "attribution": "Stephen King", "weight": 7},
        {"text": "Fiction is the truth inside the lie.", "attribution": "Stephen King", "weight": 8},
        {"text": "The scariest moment is always just before you start.", "attribution": "Stephen King", "weight": 7},
        {"text": "Quiet people have the loudest minds.", "attribution": "Stephen Hawking", "weight": 8},
        {"text": "Melancholy is the pleasure of being sad.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "To die is nothing; but it is terrible not to live.", "attribution": "Victor Hugo", "weight": 9},
        {"text": "Laughter is the sun that drives winter from the human face.", "attribution": "Victor Hugo", "weight": 7},
        {"text": "He who opens a school door, closes a prison.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "Even the darkest night will end and the sun will rise.", "attribution": "Victor Hugo", "weight": 9},
        {"text": "It is a sad thing to think that nature speaks and mankind does not listen.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "Music expresses that which cannot be put into words and that which cannot remain silent.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "Initiative is doing the right thing without being told.", "attribution": "Victor Hugo", "weight": 6},
        {"text": "Reason is intelligence taking exercise. Imagination is intelligence with an erection.", "attribution": "Victor Hugo", "weight": 7},
        {"text": "Our acts make or mar us, we are the children of our own deeds.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "The future has several names. For the weak, it is impossible; for the fainthearted, it is unknown; but for the valiant, it is ideal.", "attribution": "Victor Hugo", "weight": 9},
        {"text": "There is nothing like a dream to create the future.", "attribution": "Victor Hugo", "weight": 8},
        {"text": "To love another person is to see the face of God.", "attribution": "Victor Hugo", "weight": 9},
        {"text": "Forty is the old age of youth; fifty the youth of old age.", "attribution": "Victor Hugo", "weight": 6},
        {"text": "Life's great happiness is to be convinced we are loved.", "attribution": "Victor Hugo", "weight": 8}
    ],
    "chaos": [
        {"text": "I am entirely made of flaws, stitched together with good intentions.", "attribution": "Augusten Burroughs", "weight": 8},
        {"text": "I embrace the chaos. It is the only thing that makes sense.", "attribution": "Anonymous", "weight": 8},
        {"text": "You must have chaos within you to give birth to a dancing star.", "attribution": "Friedrich Nietzsche", "weight": 9},
        {"text": "Only those who will risk going too far can possibly find out how far one can go.", "attribution": "T.S. Eliot", "weight": 8},
        {"text": "Normal is an illusion. What is normal for the spider is chaos for the fly.", "attribution": "Charles Addams", "weight": 9},
        {"text": "The world is a tragedy to those who feel, but a comedy to those who think.", "attribution": "Horace Walpole", "weight": 8},
        {"text": "Art is nothing but a localized, physical expression of a cosmic, spiritual chaos.", "attribution": "Carl Jung", "weight": 8},
        {"text": "I can resist everything except temptation.", "attribution": "Oscar Wilde", "weight": 8},
        {"text": "Not all those who wander are lost.", "attribution": "J.R.R. Tolkien", "weight": 7},
        {"text": "We are all mad here.", "attribution": "Lewis Carroll", "weight": 9},
        {"text": "In a mad world, only the mad are sane.", "attribution": "Akira Kurosawa", "weight": 9},
        {"text": "I knew who I was this morning, but I've changed a few times since then.", "attribution": "Lewis Carroll", "weight": 8},
        {"text": "Begin at the beginning, and go on till you come to the end: then stop.", "attribution": "Lewis Carroll", "weight": 7},
        {"text": "Why, sometimes I've believed as many as six impossible things before breakfast.", "attribution": "Lewis Carroll", "weight": 8},
        {"text": "Curiouser and curiouser!", "attribution": "Lewis Carroll", "weight": 7},
        {"text": "Imagination is the only weapon in the war against reality.", "attribution": "Lewis Carroll", "weight": 9},
        {"text": "If you don't know where you are going, any road will get you there.", "attribution": "Lewis Carroll", "weight": 8},
        {"text": "It is no measure of health to be well adjusted to a profoundly sick society.", "attribution": "Jiddu Krishnamurti", "weight": 9},
        {"text": "Chaos is a friend of mine.", "attribution": "Bob Dylan", "weight": 8},
        {"text": "There is no exquisite beauty... without some strangeness in the proportion.", "attribution": "Edgar Allan Poe", "weight": 9},
        {"text": "I have found both freedom and safety in my madness; the freedom of loneliness and the safety from being understood.", "attribution": "Kahlil Gibran", "weight": 9},
        {"text": "The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.", "attribution": "George Bernard Shaw", "weight": 10},
        {"text": "Do I contradict myself? Very well, then I contradict myself, I am large, I contain multitudes.", "attribution": "Walt Whitman", "weight": 9},
        {"text": "Reality is merely an illusion, albeit a very persistent one.", "attribution": "Albert Einstein", "weight": 8},
        {"text": "I like nonsense, it wakes up the brain cells.", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "Today you are You, that is truer than true. There is no one alive who is Youer than You.", "attribution": "Dr. Seuss", "weight": 8},
        {"text": "Sometimes the questions are complicated and the answers are simple.", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "Don't cry because it's over, smile because it happened.", "attribution": "Dr. Seuss", "weight": 6},
        {"text": "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "Unless someone like you cares a whole awful lot, Nothing is going to get better. It's not.", "attribution": "Dr. Seuss", "weight": 8},
        {"text": "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "I am weird, you are weird. Everyone in this world is weird. One day two people come together in mutual weirdness and fall in love.", "attribution": "Dr. Seuss", "weight": 8},
        {"text": "From there to here, from here to there, funny things are everywhere.", "attribution": "Dr. Seuss", "weight": 7},
        {"text": "A person's a person, no matter how small.", "attribution": "Dr. Seuss", "weight": 6},
        {"text": "It's better to be absolutely ridiculous than absolutely boring.", "attribution": "Marilyn Monroe", "weight": 8},
        {"text": "Imperfection is beauty, madness is genius.", "attribution": "Marilyn Monroe", "weight": 8},
        {"text": "Dogs never bite me. Just humans.", "attribution": "Marilyn Monroe", "weight": 7},
        {"text": "Keep smiling, because life is a beautiful thing and there's so much to smile about.", "attribution": "Marilyn Monroe", "weight": 6},
        {"text": "A girl should be two things: classy and fabulous.", "attribution": "Coco Chanel", "weight": 6},
        {"text": "In order to be irreplaceable one must always be different.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "I don't care what you think about me. I don't think about you at all.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "Fashion changes, but style endures.", "attribution": "Coco Chanel", "weight": 7},
        {"text": "The most courageous act is still to think for yourself. Aloud.", "attribution": "Coco Chanel", "weight": 9},
        {"text": "There is no time for cut-and-dried monotony. There is time for work. And time for love. That leaves no other time.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "Success is most often achieved by those who don't know that failure is inevitable.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "As long as you know men are like children, you know everything!", "attribution": "Coco Chanel", "weight": 7},
        {"text": "Simplicity is the keynote of all true elegance.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "Nature gives you the face you have at twenty; it is up to you to merit the face you have at fifty.", "attribution": "Coco Chanel", "weight": 8},
        {"text": "A woman who doesn't wear perfume has no future.", "attribution": "Coco Chanel", "weight": 6}
    ]
}

# Ensure the assets/data directory exists
os.makedirs('assets/data', exist_ok=True)

# Write to JSON
with open('assets/data/tomes.json', 'w') as f:
    json.dump(tomes_data, f, indent=2)

print(f"Generated assets/data/tomes.json with 50 high-quality quotes per tome (300 total)!")
